url: http://www.daryproduct.com

# Site settings
title: daryproduct
email: dary@daryproduct.com
description: "Personal website for a product dreamer, thinker, designer and marketer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty

port: 7000

sass:
  sass_dir: assets/css
  style: :nested
