# Site settings
title: daryproduct
email: dary@daryproduct.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

port: 7000

sass:
  sass_dir: assets/css
  style: :nested
