#-------------------------------
# General Site Settings

title: daryproduct
description: Think // Design // Create // Market
email: dary@daryproduct.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#work'}
- {name: Experiences, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal website for a product dreamer, thinker, designer and marketer.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

skills:
- {name: Communication, value: '7'}
- {name: Planning, value: '8'}
- {name: Architectural Design, value: '6'}
- {name: UX Design, value: '5'}
- {name: Visual Design, value: '8'}
- {name: Project Management, value: '7'}
- {name: Programming, value: '1'}
- {name: Product Marketing, value: '8'}

#-------------------------------
# Work Section

portfolio:
- {name: Canal City Competition, folder: 'proj-1', file: 'portfolio/proj-1.html', modal-id: '1', client: 'Personal', project-date: '2009-12-15', category: 'Architecture'}
- {name: Foster City Elementary School, folder: 'proj-2', file: 'portfolio/proj-2.html', modal-id: '2', client: 'WLC', project-date: '2011-09-16', category: 'Architecture'}
- {name: Assimilation, folder: 'proj-3', file: 'portfolio/proj-3.html', modal-id: '3', client: 'Personal', project-date: '2007-07-12', category: 'Photography'}
- {name: kiteworks Microsite, folder: 'proj-4', file: 'portfolio/proj-4.html', modal-id: '4', client: 'Accellion', project-date: '2014-12-10', category: 'Marketing'}
- {name: kiteworks Videos, folder: 'proj-5', file: 'portfolio/proj-5.html', modal-id: '5', client: 'Accellion', project-date: '2015-06-30', category: 'Marketing'}
- {name: Settlr, folder: 'proj-6', file: 'portfolio/proj-6.html', modal-id: '6', client: 'Personal', project-date: '2015-07-05', category: 'UI/UX Design'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'DataSift-logo.jpg',
  name: 'DataSift',
  title: 'Product Marketing Manager',
  quote: '<h5>September 2015 - Present</h5>
          <p><li>Develop marketing strategies and campaigns to drive awareness and growth of the PYLON social analytics platform for Facebook Topic Data; results in 3x growth in customer base within 12 months</li></p>
          <p><li>Define product messaging to educate prospects and customers about the use cases, best practices, and benefits</li></p>
          <p><li>Execute product launch plan for new product and feature releases from handling internal and customer communication to creating marketing collaterals such as web content, datasheet, whitepapers, and blogs</li></p>
          <p><li>Enable sales and services to sell the DataSift story effectively through sales training and creating sales collaterals such as product presentations, product guides, and competitive briefs</li></p>
          <p><li>Drive demand generation and content marketing activities including webinar, e-newsletter, and automated free trial; results in an average of 22% increase in content engagement and 30% increase in trial signups</li></p>
          <p><li>Lead the partner success initiative to drive success of the ecosystem including creating partner toolkit and microsite</li></p>',
  logo: 'logo1.png'}
- {avatar: 'Accellion-logo.jpg',
  name: 'Accellion',
  title: 'Associate Product Marketing Manager',
  quote: '<h5>June 2013 - September 2015</h5>
          <p><li>Managed Accellion’s kiteworks content platform by monitoring product performance, designing marketing programs to drive product awareness, developing content for lead generation, and enabling sales with new releases</li></p>
          <p><li>Developed vertical marketing strategy and content to increase adoption in the legal industry by 10%</li></p>
          <p><li>Increased mobile app conversion through app store optimization and implementing in-app tutorials</li></p>
          <p><li>Created outbound collaterals (data sheets, web content, microsite, videos, white papers, blogs, infographics, etc.) and internal sales tools (ROI calculator, sales alerts, battle cards, etc.)</li></p>
          <p><li>Collaborated cross-functionally with PMs, engineers, internal creative team, and external vendors</li></p>',
  logo: 'logo2.png'}
- {avatar: 'Box-logo.jpg',
  name: 'Box',
  title: 'Customer Success Operations Intern',
  quote: '<h5>May 2012 - September 2012</h5>
          <p><li>Automated in-app upgrade conversion process with Engineering to reduce man-hours by 70%</li></p>
          <p><li>Developed strategy to streamline account cancellation process by identifying dependencies</li></p>
          <p><li>Built Salesforce reports to quantify upsell opportunities and forecast account growth</li></p>',
  logo: 'logo3.png'}
- {avatar: 'WLC-logo.jpg',
  name: 'WLC Architects',
  title: 'Designer',
  quote: '<h5>August 2008 - September 2011</h5>
          <p><li>Conducted client workshops and design charades to discover client needs</li></p>
          <p><li>Generated sustainable design concepts using innovative building technology and materials</li></p>
          <p><li>Developed master plan, schematic, design, construction drawings for state agency review</li></p>
          <p><li>Collaborated with engineers and consultants on project development from concept to construction</li></p>',
  logo: 'logo4.png'}


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/daryhsu
  - title: flickr
    url: https://www.flickr.com/photos/daryproduct
  - title: dribbble
    url: https://dribbble.com/daryproduct
  - title: instagram
    url: https://instagram.com/daryproduct/
  - title: linkedin
    url: http://www.linkedin.com/in/daryhsu/
