#-------------------------------
# General Site Settings

title: daryproduct
description: Think // Design // Create // Market
email: dary@daryproduct.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#projects'}
- {name: Experiences, url: '#experiences'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  A **dreamer** who won't stop pursuing the **passion** of **creating products** that would,
  cliche, make the world a better place. A good **design** is not only a must but
  automatically becomes a happy byproduct of such pursue.

#  **Travis specializes in making things** for human people.
#  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
#  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
#  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.


skills:
- {name: Communication, value: '9'}
- {name: Marketing, value: '7'}
- {name: Planning, value: '10'}
- {name: UX Design, value: '5'}
- {name: Visual Design, value: '7'}
- {name: Project Management, value: '5'}
- {name: Programming, value: '8'}
- {name: Product Marketing, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Canal City Competition, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Foster City Elementary School, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'Accellion-logo.jpg',
  name: 'Accellion',
  title: 'Product Marketing Manager',
  quote: '<h5>June 2013 - Present</h5>
          <p><li>Drive mobile solution adoption by creating personas/storyboard to understand user workflow, and defining metrics to increase mobile app adoption by analyzing customer usage, reviews, and competitors</li></p>
          <p><li>Develop vertical marketing strategy and materials to drive product adoption in the legal industry; present to global sales force in a sales training webinar</li></p>
          <p><li>Execute product launch plan including planning launch event, updating datasheets and web contents, preparing analyst briefing materials, and creating sales alert and use cases to demonstrate product features</li></p>
          <p><li>Collaborate on product development with cross-functional team of sales, product management, public relations</li></p>
          <p><li>Enhance mobile app UX through usability research; monitor competitor and industry trends to make product feature recommendations</li></p>
          <p><li>Create internal sales materials and outbound marketing collaterals such as datasheet, web content, blogs, e-newsletter</li></p>',
  logo: 'logo1.png'}
- {avatar: 'Box-logo.jpg',
  name: 'Box',
  title: 'Customer Success Operations Intern',
  quote: '<h5>May 2012 - September 2012</h5>
          <p><li>Collaborated with Engineering to automate in-app upgrade conversion process and reduce man-hours by 70%</li></p>
          <p><li>Developed strategy to streamline Billing Operations cancellation process by identifying dependencies</li></p>
          <p><li>Oversaw entire customer lifecycle from provisioning to close lost accounts in Salesforce and internal tools</li></p>
          <p><li>Built Salesforce reports to quantify Client Services upsell opportunities and account growth forecasts</li></p>',
  logo: 'logo2.png'}
- {avatar: 'WLC-logo.jpg',
  name: 'WLC Architects',
  title: 'Designer',
  quote: '<h5>August 2008 - September 2011</h5>
          <p><li>Generated unique design concepts with innovative building systems and materials that incorporates guidelines from design charades with clients</li></p>
          <p><li>Coordinated cross function consultant team to provide integrative, comprehensive solutions while enhancing productivity and communication</li></p>
          <p><li>Created marketing proposals and meeting presentation materials that successfully increased number of request for proposals and new projects</li></p>
          <p><li>Generated preliminary project schedule and budget estimates</li></p>
          <p><li>Developed master plan, schematic, design, construction drawings for state agency DSA submittal</li></p>',
  logo: 'logo3.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/daryhsu'}
- {icon: 'dribbble', link: 'https://dribbble.com/daryproduct'}
- {icon: 'behance', link: 'https://www.behance.net/daryproduct'}
- {icon: 'youtube', link: 'https://www.flickr.com/photos/daryproduct'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/daryhsu/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
