#-------------------------------
# General Site Settings

title: daryproduct
description: Think // Design // Create // Market
email: dary@daryproduct.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#work'}
- {name: Experiences, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal website for a product dreamer, thinker, designer and marketer.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

skills:
- {name: Communication, value: '7'}
- {name: Planning, value: '8'}
- {name: Architectural Design, value: '6'}
- {name: UX Design, value: '5'}
- {name: Visual Design, value: '8'}
- {name: Project Management, value: '7'}
- {name: Programming, value: '1'}
- {name: Product Marketing, value: '8'}

#-------------------------------
# Work Section

portfolio:
- {name: Canal City Competition, folder: 'proj-1', file: 'portfolio/proj-1.html', modal-id: '1', client: 'Personal', project-date: '2009-12-15', category: 'Architecture'}
- {name: Foster City Elementary School, folder: 'proj-2', file: 'portfolio/proj-2.html', modal-id: '2', client: 'WLC', project-date: '2011-09-16', category: 'Architecture'}
- {name: Assimilation, folder: 'proj-3', file: 'portfolio/proj-3.html', modal-id: '3', client: 'Personal', project-date: '2007-07-12', category: 'Photography'}
- {name: kiteworks Microsite, folder: 'proj-4', file: 'portfolio/proj-4.html', modal-id: '4', client: 'Accellion', project-date: '2014-12-10', category: 'Marketing'}
- {name: kiteworks Videos, folder: 'proj-5', file: 'portfolio/proj-5.html', modal-id: '5', client: 'Accellion', project-date: '2015-06-30', category: 'Marketing'}
- {name: Settlr, folder: 'proj-6', file: 'portfolio/proj-6.html', modal-id: '6', client: 'Personal', project-date: '2015-07-05', category: 'UI/UX Design'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'DataSift-logo.jpg',
  name: 'DataSift',
  title: 'Product Marketing Manager',
  quote: '<h5>September 2015 - Present</h5>
          <p><li>Define PYLON platform and product messaging and execute product launch plan including internal and customer communication and creating outbound marketing collaterals such as datasheet, web content, blogs and more</li></p>
          <p><li>Led partner success initiative by creating partner sales toolkit for customer marketing success and greater upsell opportunities</li></p>
          <p><li>Drive demand generation and content marketing activities including webinar, e-newsletter, ads targeting and event planning</li></p>
          <p><li>Enable sales by conducting sales training sessions and creating sales deck, battle cards, account-based marketing and more</li></p>
          <p><li>Rsearch potential new market for PYLON for Facebook topic data to increase addressable market for Facebook topic data</li></p>',
  logo: 'logo1.png'}
- {avatar: 'Accellion-logo.jpg',
  name: 'Accellion',
  title: 'Associate Product Marketing Manager',
  quote: '<h5>June 2013 - September 2015</h5>
          <p><li>Drive mobile solution adoption by creating personas/storyboard to understand user workflow, and defining metrics to increase mobile app adoption by analyzing customer usage, reviews, and competitors</li></p>
          <p><li>Develop vertical marketing strategy and materials to drive product adoption in the legal industry; present to global sales force in a sales training webinar</li></p>
          <p><li>Execute product launch plan including planning launch event, updating datasheets and web contents, preparing analyst briefing materials, and creating sales alert and use cases to demonstrate product features</li></p>
          <p><li>Collaborate on product development with cross-functional team of sales, product management, public relations</li></p>
          <p><li>Create internal sales materials and outbound marketing collaterals such as datasheet, web content, blogs, e-newsletter</li></p>',
  logo: 'logo2.png'}
- {avatar: 'Box-logo.jpg',
  name: 'Box',
  title: 'Customer Success Operations Intern',
  quote: '<h5>May 2012 - September 2012</h5>
          <p><li>Collaborated with Engineering to automate in-app upgrade conversion process and reduce man-hours by 70%</li></p>
          <p><li>Developed strategy to streamline Billing Operations cancellation process by identifying dependencies</li></p>
          <p><li>Oversaw entire customer lifecycle from provisioning to close lost accounts in Salesforce and internal tools</li></p>
          <p><li>Built Salesforce reports to quantify Client Services upsell opportunities and account growth forecasts</li></p>',
  logo: 'logo3.png'}
- {avatar: 'WLC-logo.jpg',
  name: 'WLC Architects',
  title: 'Designer',
  quote: '<h5>August 2008 - September 2011</h5>
          <p><li>Generated unique design concepts with innovative building systems and materials that incorporates guidelines from design charades with clients</li></p>
          <p><li>Coordinated cross function consultant team to provide integrative, comprehensive solutions while enhancing productivity and communication</li></p>
          <p><li>Created marketing proposals and meeting presentation materials that successfully increased number of request for proposals and new projects</li></p>
          <p><li>Generated preliminary project schedule and budget estimates</li></p>
          <p><li>Developed master plan, schematic, design, construction drawings for state agency DSA submittal</li></p>',
  logo: 'logo4.png'}


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/daryhsu
  - title: flickr
    url: https://www.flickr.com/photos/daryproduct
  - title: dribbble
    url: https://dribbble.com/daryproduct
  - title: instagram
    url: https://instagram.com/daryproduct/
  - title: linkedin
    url: http://www.linkedin.com/in/daryhsu/
